name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
      - master

pr: none

variables:
  - group: ReactAppEnvVars

steps:
  - task: Docker@2
    displayName: Build
    inputs:
      command: build
      arguments: |
        --build-arg REACT_APP_MAPBOX_ACCESS_TOKEN=$(reactAppMapboxAccessToken)
        --build-arg REACT_APP_CUTLER_MAP_STYLE_ID=$(reactAppCutlerMapStyleId)
        --build-arg REACT_APP_FIREBASE_API_KEY=$(reactAppFirebaseApiKey)
        --build-arg REACT_APP_FIREBASE_AUTH_DOMAIN=$(reactAppFirebaseAuthDomain)
        --build-arg REACT_APP_FIREBASE_DATABASE_URL=$(reactAppFirebaseDatabaseUrl)
        --build-arg REACT_APP_FIREBASE_PROJECT_ID=$(reactAppFirebaseProjectId)
        --build-arg REACT_APP_FIREBASE_STORAGE_BUCKET=$(reactAppFirebaseStorageBucket)
        --build-arg REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$(reactAppFirebaseMessagingSenderId)
        --build-arg REACT_APP_FIREBASE_APP_ID=$(reactAppFirebaseAppId)
      containerRegistry: cutlercr
      repository: cutler
      tags: |
        latest
  - task: Docker@2
    displayName: Push
    inputs:
      command: push
      containerRegistry: cutlercr
      repository: cutler
      tags: |
        latest
