FROM node:12.16-alpine as react-build
WORKDIR /app
COPY frontend .
ARG REACT_APP_MAPBOX_ACCESS_TOKEN
ARG REACT_APP_CUTLER_MAP_STYLE_ID
ARG REACT_APP_FIREBASE_API_KEY
ARG REACT_APP_FIREBASE_AUTH_DOMAIN
ARG REACT_APP_FIREBASE_DATABASE_URL
ARG REACT_APP_FIREBASE_PROJECT_ID
ARG REACT_APP_FIREBASE_STORAGE_BUCKET
ARG REACT_APP_FIREBASE_MESSAGING_SENDER_ID
ARG REACT_APP_FIREBASE_APP_ID
ENV REACT_APP_MAPBOX_ACCESS_TOKEN ${REACT_APP_MAPBOX_ACCESS_TOKEN}
ENV REACT_APP_CUTLER_MAP_STYLE_ID ${REACT_APP_CUTLER_MAP_STYLE_ID}
ENV REACT_APP_FIREBASE_API_KEY ${REACT_APP_FIREBASE_API_KEY}
ENV REACT_APP_FIREBASE_AUTH_DOMAIN ${REACT_APP_FIREBASE_AUTH_DOMAIN}
ENV REACT_APP_FIREBASE_DATABASE_URL ${REACT_APP_FIREBASE_DATABASE_URL}
ENV REACT_APP_FIREBASE_PROJECT_ID ${REACT_APP_FIREBASE_PROJECT_ID}
ENV REACT_APP_FIREBASE_STORAGE_BUCKET ${REACT_APP_FIREBASE_STORAGE_BUCKET}
ENV REACT_APP_FIREBASE_MESSAGING_SENDER_ID ${REACT_APP_FIREBASE_MESSAGING_SENDER_ID}
ENV REACT_APP_FIREBASE_APP_ID ${REACT_APP_FIREBASE_APP_ID}
RUN yarn install
RUN yarn run build

FROM node:12.16-alpine
WORKDIR /app
COPY . .
COPY --from=react-build /app/build frontend/build
WORKDIR /app/server
RUN yarn install
RUN yarn run build
ENV NODE_ENV=production
CMD [ "yarn", "start" ]
