import {
  EURO_UNIT,
  EURO_PER_SQUARED_METER_UNIT,
  METER_UNIT,
  PERCENT_UNIT,
} from './utils/units';

export const mapLayersUnitId = {
  'direct benefit of garden street type 1 per m2': EURO_PER_SQUARED_METER_UNIT,
  'direct benefit of garden street type 2 per m2': EURO_PER_SQUARED_METER_UNIT,
  'direct benefit of garden street type 3 per m2': EURO_PER_SQUARED_METER_UNIT,
  'public green surface 2020': PERCENT_UNIT,
  'unpaved public space 2020': PERCENT_UNIT,
  'inhabitants within 2-5 min. from green space': PERCENT_UNIT,
  'Average rent residential 2018': EURO_UNIT,
  'Average price apartments 2014': EURO_UNIT,
  'Average price commercial and industrial real estate 2014': EURO_UNIT,
  'Average house price 2014': EURO_UNIT,
  // 'Poverty Index 2015': unitless,
  'Percent increase in house prices if no T5 flooding': PERCENT_UNIT,
  'Percent increase in house prices if no T20 flooding': PERCENT_UNIT,
  'Percent increase in house prices if no T100 flooding': PERCENT_UNIT,
  'Percent increase in apartment prices if no T5 flooding': PERCENT_UNIT,
  'Percent increase in apartment prices if no T20 flooding': PERCENT_UNIT,
  'Percent increase in apartment prices if no T100 flooding': PERCENT_UNIT,
  'Percent increase in commercial estate prices if no T5 flooding': PERCENT_UNIT,
  'Percent increase in commercial estate prices if no T20 flooding': PERCENT_UNIT,
  'Percent increase in commercial estate prices if no T100 flooding': PERCENT_UNIT,
  'Percent increase in all estate prices if no T5 flooding': PERCENT_UNIT,
  'Percent increase in all estate prices if no T20 flooding': PERCENT_UNIT,
  'Percent increase in all estate prices if no T100 flooding': PERCENT_UNIT,
  'Percent increase in residential rents if no T5 flooding': PERCENT_UNIT,
  'Percent increase in residential rents if no T20 flooding': PERCENT_UNIT,
  'Percent increase in residential rents if no T100 flooding': PERCENT_UNIT,
  'Flooding depth T05': METER_UNIT,
  'Flooding depth T20': METER_UNIT,
  'Flooding depth T100': METER_UNIT,
};
